name: Terraform Apply (Pre-Merge)

on:
  pull_request_review:
    types: [submitted]  # Runs when a PR review is submitted

permissions:
  contents: read
  pull-requests: read

jobs:
  terraform-apply:
    if: github.event.review.state == 'approved'
    name: Apply Terraform Changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your region

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
