name: Terraform Plan

on:
  pull_request:
    branches:
      - main

jobs:
  tflint-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Install tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Terraform Init
        run: terraform init

      - name: Run Terraform Linter (tflint)
        run: tflint --init
        continue-on-error: false  # Fail the workflow if linting fails

  tfsec-check:
    runs-on: ubuntu-latest
    needs: tflint-check  # This makes tfsec-check depend on tflint-check

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Install tfsec
        run: |
          curl -sSL https://github.com/aquasecurity/tfsec/releases/download/v1.21.0/tfsec-linux-amd64 -o tfsec
          chmod +x tfsec
          mv tfsec /usr/local/bin/tfsec

      - name: Terraform Init
        run: terraform init

      - name: Run tfsec (Security Check)
        run: tfsec .  # Run tfsec security scan

  terraform-plan:
    runs-on: ubuntu-latest
    needs: tfsec-check  # This makes terraform-plan depend on tfsec-check

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
